Django_portafolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portafolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('blog/', include('blog.urls')),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from importlib.resources import path
from unicodedata import name
from django import views
from django.urls import path
from .views import render_post, post_detail

app_name = 'blog'

urlpatterns = [
    path('', render_post, name='posts'),
    path('<int:post_id>', post_detail, name="post_detail")
]

blog/models.py
from distutils.command.upload import upload
from turtle import title
from django.db import models
import datetime

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100) 
    description = models.TextField()
    image = models.ImageField(upload_to="blog/images")
    date = models.DateField(datetime.date.today)

portafolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField

class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to='portafolio/images/')
    url = URLField(blank=True)
    

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

# Create your views here.
def render_post(request):
    posts = Post.objects.all()
    return render(request, 'post.html', {'posts': posts})

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {'post': post})

portafolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def index(request):
    projects = Project.objects.all()

    return render(request, 'index.html', {'projects':projects}) 

blog/templates/post.html
{% extends 'layout.html'%}

{% block content %}

{% for post in posts %}

    <div class="p-3">
        <div class="card-body">
            <div class="row card-project">
    
                <div class="col-3">
                    <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
                    
                </div>
    
                <div class="col-9">
                    <h2>{{post.title}}</h2>
                    <p>{{post.date}}</p>
                    <p>{{post.description|truncatechars:100}}</p>
                    <a href="{% url 'blog:post_detail' post.id %}" 
                    class="btn btn-primary ">{{post.title}}</a>
                </div>
            </div>
        </div>
    </div>
{% endfor %}

{% endblock %}

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}

<div class="text-center">
    <h2>{{post.title}}</h2>
    <h3 class="my-2 h5 text-muted">{{post.date|date:'F jS Y'}}</h3>

    <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">

    <div class="my-4">
        <p>{{post.description|safe}}</p>
    </div>
</div>


{% endblock %}

portafolio/templates/home.html
{% extends 'layout.html'%}


{% block content %}

{% load static %}

<header class="row bg-black text-center">
    <div class="col-md-4">
        <img 
        src="{% static 'portfolio/IMG_JTA.jpg'%}" 
        class="img-fluid">
    </div>
    <div class="col-md-8 my-auto" >
        <h1><strong>Jhonnier Tangarife Ardila</strong></h1>
        <h3>Engineer Control and Instrumentation</h3>
        <a 
        href="{% static 'portfolio/Curriculum2022.pdf'%} " 
        class="btn btn-primary btn-lg rounded-0 my-3 ">
            Download CV
        </a>
    </div>
    
</header>

<div class="row my-4 text-center">
    
    <h3>My Projets</h3>
    {% for project in projects%}

        <div class="col-md-4 p-4">
            <div class="card bg-black card-project">
                <img src="{{project.image.url}}" alt="{{projetc.title}}" class="card-img-top">
                
                <div class="card-body">
                    <h2>{{project.title}}</h2><p>{{project.description}}</p>
                    
                    {% if project.url %}
                        <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="_blank">{{project.url}}</a>
                    {% endif %}
                </div>
            </div>
        
        </div>
    
        {% endfor %}    
        
        {% endblock %}
    </div>

portafolio/templates/index.html
{% extends 'layout.html'%}


{% block content %}

{% load static %}

<header class="row bg-black text-center">
    <div class="col-md-4">
        <img 
        src="{% static 'portfolio/IMG_JTA.jpg'%}" 
        class="img-fluid">
    </div>
    <div class="col-md-8 my-auto" >
        <h1><strong>Jhonnier Tangarife Ardila</strong></h1>
        <h3>Engineer Control and Instrumentation</h3>
        <a 
        href="{% static 'portfolio/Curriculum2022.pdf'%} " 
        class="btn btn-primary btn-lg rounded-0 my-3 ">
            Download CV
        </a>
    </div>
    
</header>

<div class="row my-4 text-center">
    
    <h3>My Projets</h3>
    {% for project in projects%}

        <div class="col-md-4 p-4">
            <div class="card bg-black card-project">
                <img src="{{project.image.url}}" alt="{{projetc.title}}" class="card-img-top">
                
                <div class="card-body">
                    <h2>{{project.title}}</h2><p>{{project.description}}</p>
                    
                    {% if project.url %}
                        <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="_blank">{{project.url}}</a>
                    {% endif %}
                </div>
            </div>
        
        </div>
    
        {% endfor %}    
        
        {% endblock %}
    </div>

portafolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Portafolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
     <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="text-light">
    
        {% include 'partials/navbar.html'%}
        <div class="contaniner p-5">
            {% block content%}
            {% endblock %}
        </div> 
</body>
</html>

portafolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/" fw-bold fst-ital><strong>Jhonnnier Tangarife Ardila</strong></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ms-auto d-flex align-items-center" >
          <a class="nav-link active" aria-current="page" href="{% url 'blog:posts' %}">Blog</a>
          <a class="btn btn-primary btn-sm" 
          href="{% static 'portfolio/Curriculum2022.pdf'%}"
          target="_blank">Download CV</a>
        </div>
      </div> 
    </div>
  </nav>